### ISSUE TITLE
Code Block Formatting on EightShapes.com Medium Posts

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/eightshapes-com#150]
http://localhost:3000/articles/design-system-subtasks-by-step.html

This article isn't working with the esds code formatting web component, at two locations now just using PRE tags to post as is:

![image](https://user-images.githubusercontent.com/1165904/73990173-63299880-4916-11ea-86de-1db782bafcad.png)

![image](https://user-images.githubusercontent.com/1165904/73990189-6a50a680-4916-11ea-8f26-ca69c49560ca.png)

**Comment by kevinmpowell** [comment]
@nathanacurtis be sure to close the nunjucks markdown filter before calling the code snippet webcomponent. For some reason the markdown filter breaks the web component usage.

I've fixed for this article and committed to master.

![image](https://user-images.githubusercontent.com/979463/74171290-f6ebb500-4bf3-11ea-9e2c-77b6c6debcd1.png)

**Comment by nathanacurtis** [comment]
@kevinmpowell Got it! Defect in component user confirmed!
